<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Interview instruction</name>
   <tag></tag>
   <elementGuidId>a6784a15-e06d-4bde-82f4-79267deaa405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div/div[2]/div/div[2]/div/form/div/div[2]/div[4]/div[2]/div/div/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div[2]/div/div[2]/div/form/div/div[2]/div[4]/div[2]/div/div/div/textarea</value>
      <webElementGuid>5db312d2-6a62-4671-84a9-e34c9bd4b40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7697f51c-b655-424a-b9e9-442a4c15411f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>interviewInstructions</value>
      <webElementGuid>87f9fd7b-1f34-41fc-b021-c559bab0abba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
