<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save icon</name>
   <tag></tag>
   <elementGuidId>0ad9549c-d221-4864-bd0d-a9d2fdfd926b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class=&quot;saved-job-enter-done&quot;][1]//*[@class=&quot;job-card-saved-icon&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class=&quot;saved-job-enter-done&quot;][1]//*[@class=&quot;job-card-saved-icon&quot;]</value>
   </webElementProperties>
</WebElementEntity>
