<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Uploaded image</name>
   <tag></tag>
   <elementGuidId>44c3789d-938f-4e99-a43a-37f9ad660d58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='personal-information']/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.preload-image-container.user-avatar-image-container.-profile > img.preload-image.user-avatar-image.-show</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>preload-image user-avatar-image -show</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://stwanpngcommonsdev.blob.core.windows.net/job-seekers-photo/798d48ce14f27f1c025a6e759276dca267f416b7d8.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal-information&quot;)/div[@class=&quot;personal-information-form-container&quot;]/div[@class=&quot;avatar-upload-photo-container&quot;]/div[@class=&quot;preload-image-container user-avatar-image-container -profile&quot;]/img[@class=&quot;preload-image user-avatar-image -show&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='personal-information']/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://stwanpngcommonsdev.blob.core.windows.net/job-seekers-photo/798d48ce14f27f1c025a6e759276dca267f416b7d8.jpg')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://stwanpngcommonsdev.blob.core.windows.net/job-seekers-photo/798d48ce14f27f1c025a6e759276dca267f416b7d8.jpg']</value>
   </webElementXpaths>
</WebElementEntity>
