<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>First option jobtitle</name>
   <tag></tag>
   <elementGuidId>188f4f97-021f-47d8-a3ec-8bc7c049d022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div/div/div/div[2]/div[1]/div/div/div[1]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>invite-to-apply-select-input-option-title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div/div/div[2]/div[1]/div/div/div[1]/div/div/span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div/div/div[2]/div[1]/div/div/div[1]/div/div/span

//div[@class=&quot;ant-select-item-option-content&quot;]//div[@class=&quot;invite-to-apply-select-input-option-container&quot;][1]//span[@class=&quot;invite-to-apply-select-input-option-title&quot;][1]</value>
   </webElementProperties>
</WebElementEntity>
