<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Clean Work experience Section</name>
   <tag></tag>
   <elementGuidId>28eb0a60-3e03-411e-a15c-5e1104da81ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cleanProfileContainer-0-2-96</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/section/section/div/div/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cleanProfileContainer-0-2-96</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work experienceDatabase ManagementWan PNGClark Freeport ZoneApril 2020 - Present •  6 months Nunc sagittis enim a lobortis egestas. Aliquam ultrices erat neque, nec ornare sapien euismod eu. Morbi interdum quam ac condimentum faucibus. Fusce consectetur sed nisl ut rhoncus. Morbi eleifend fermentum nunc, sed dignissim quam tincidunt eu. Vestibulum vitae feugiat velit, non fringilla nisi. In odio tortor, pellentesque eu lacus ut, ultricies venenatis neque. Sed vestibulum metus eget felis efficitur euismod. Nullam tincidunt turpis diam, quis auctor lectus interdum at.Front-End DeveloperUbidyClark Freeport ZoneMarch 2016 - April 2020 • 4 years 2 months Cras dictum sollicitudin sapien, dictum tristique turpis interdum non. Integer rutrum, metus sed aliquet rhoncus, ipsum diam facilisis metus, quis ullamcorper orci sapien sed urna. Nunc sit amet finibus diam. Curabitur molestie felis nibh, ut mattis nunc sollicitudin vel. Proin gravida tempor dui, eu ultrices risus tincidunt ut. Fusce feugiat semper turpis quis hendrerit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras a malesuada metus, sed mattis lacus. Praesent sit amet eleifend magna, ut sodales nibh. Sed volutpat id mauris ac lobortis. Aliquam dictum, lorem eu cursus luctus, nulla urna aliquam metus, quis laoreet lectus ex a sem. Curabitur non fermentum justo, eu ullamcorper arcu. Nunc quis eleifend libero, et maximus eros.Back-End DeveloperGold CorporationMabalacat CityJuly 2010 - March 2015 • 4 years 9 months Maecenas ac suscipit mi. Etiam ut porta tortor. Suspendisse suscipit eu arcu nec dictum. Vivamus rhoncus dolor id mattis iaculis. Praesent rutrum est vitae venenatis suscipit. Donec ac metus quis ipsum vulputate volutpat. Curabitur ut magna aliquet est tempor pulvinar.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/main/section/section/div/div/div[2]/div[3]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/section/div/div/div[2]/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPL 353'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
