<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Clean Training Section</name>
   <tag></tag>
   <elementGuidId>ac5869a8-3b79-48c1-b716-29ebd23d19b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/section/section/div/div/div[2]/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cleanProfileContainer-0-2-96</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TrainingCloudstaff PhilippinesSoftware Quality AssuranceMay 2018 - May 2018Fusce porttitor semper fermentum. Suspendisse volutpat luctus erat, a fermentum eros rutrum eget. Nam nisi orci, feugiat id dolor a, malesuada gravida erat. Vivamus sem sapien, semper id arcu id, laoreet mollis arcu. Morbi hendrerit turpis id ante bibendum, sed tempor odio consequat. Aliquam a lectus sed leo mattis luctus. Suspendisse volutpat tortor tellus, sit amet aliquet odio pulvinar non. Nulla volutpat fermentum laoreet. Mauris sed nunc ultricies, tempus arcu sit amet, ornare odio. Morbi egestas odio at ligula efficitur iaculis. Nam imperdiet diam et mi cursus elementum. Sed eget bibendum lacus.Angeles University FoudationWebinar Automation Best PracticesMarch 2018 - March 2018Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ultrices augue accumsan nibh dictum facilisis. Phasellus est mauris, pretium at ullamcorper sit amet, condimentum ut sem. Fusce mollis felis est, blandit porta velit commodo id. Duis malesuada lectus eu eleifend fermentum. Nullam consectetur tempus ligula, sit amet efficitur felis auctor sit amet. Quisque consequat, ligula at porta dapibus, nisi lectus accumsan odio, sed sagittis mi ligula sed eros. Etiam vel nibh justo.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/main/section/section/div/div/div[2]/div[5]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/section/div/div/div[2]/div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]</value>
   </webElementXpaths>
</WebElementEntity>
